<?php

namespace Database\Seeders;

use App\Models\Work;
use Illuminate\Database\Seeder;

class WorkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $works = [
            [
                'name' => 'Turbo Restaurant Platform',
                'description' => 'A multi-tenant SaaS platform enabling restaurants and cafes to launch their branded online ordering systems with integrated POS connectivity.',
                'full_description' => 'A multi-tenant SaaS platform enabling restaurants and cafes to launch their branded online ordering systems with integrated POS connectivity, real-time order management, and flexible promotional tools. Each tenant operates in an isolated environment with custom themes, localized content, and independent payment processing.',
                'problem' => 'Restaurant chains and independent venues struggle with fragmented digital ordering solutions that don\'t integrate with existing POS systems. Most platforms force a one-size-fits-all approach, lacking the flexibility needed for different brand identities, complex promotional structures, or regional operations. Deploying separate systems for each location creates operational overhead and inconsistent customer experiences.',
                'solution' => 'Built a scalable multi-tenant architecture where each restaurant operates as an independent instance with isolated tenant databases, POS synchronization, advanced promotion engine, dynamic packaging system, real-time order pipeline, multi-theme framework, and bilingual infrastructure with full Arabic/English support.',
                'role' => 'Fullstack Developer – Responsible for end-to-end feature implementation, architecture decisions, and system integration.',
                'contributions' => [
                    'Designed and implemented multi-tenancy architecture using Stancl Tenancy with SQLite/MySQL per-tenant databases',
                    'Built comprehensive coupon validation service handling complex conditional logic',
                    'Created flexible package system with nested group selection logic and variant support',
                    'Integrated Paymob and Kashier payment gateways with webhook handling',
                    'Developed POS mapping layer for product synchronization and order relay',
                    'Built React-based customer interface using Inertia.js for seamless SPA experience',
                    'Implemented multi-theme system with shadcn/ui components',
                    'Configured FilamentPHP admin interface with custom resource schemas',
                    'Set up automated testing pipeline with parallel sharding',
                ],
                'tech_stack' => [
                    [
                        'category' => 'Backend',
                        'items' => ['Laravel 12', 'PHP 8.3+', 'Stancl Tenancy', 'FilamentPHP 4', 'Laravel Sanctum', 'Pest 4'],
                    ],
                    [
                        'category' => 'Frontend',
                        'items' => ['React 18', 'TypeScript', 'Inertia.js 2', 'Tailwind CSS 4', 'shadcn/ui', 'i18next', 'Embla Carousel'],
                    ],
                    [
                        'category' => 'Infrastructure',
                        'items' => ['MySQL', 'Expo', 'Paymob & Kashier', 'Google OAuth', 'Vite'],
                    ],
                    [
                        'category' => 'Development Tools',
                        'items' => ['Larastan (PHPStan)', 'Laravel Pint', 'Rector', 'Playwright'],
                    ],
                ],
                'challenges' => [
                    [
                        'title' => 'Multi-Tenancy Data Isolation',
                        'description' => 'Ensuring complete data separation while maintaining shared codebase efficiency.',
                        'decision' => 'Implemented database-per-tenant approach with automated migration tracking. Chose this over schema-based separation for stronger isolation guarantees and simpler backup/restore procedures.',
                    ],
                    [
                        'title' => 'Complex Coupon Validation Logic',
                        'description' => 'Supporting intricate promotional rules (product restrictions, location limits, time windows, user targeting) without performance degradation.',
                        'decision' => 'Built dedicated CouponService with early-exit validation pattern. Indexed key lookup fields (code, is_active) and used JSON columns for flexible condition storage with structured validation.',
                    ],
                    [
                        'title' => 'Variant-Aware Package System',
                        'description' => 'Allowing customers to select specific product variants within meal bundles (size, spice level, etc.) while maintaining inventory accuracy.',
                        'decision' => 'Created nested group/item structure with optional variant references. Used Filament\'s reactive forms to dynamically load variant dropdowns based on product selection, preventing invalid combinations.',
                    ],
                    [
                        'title' => 'Payment Gateway Abstraction',
                        'description' => 'Supporting multiple payment providers (Paymob, Kashier) with different webhook formats and confirmation flows.',
                        'decision' => 'Built provider-agnostic order creation pipeline with webhook handlers implementing common interface. This allows adding new gateways without touching core order logic.',
                    ],
                ],
                'images' => [
                    ['image' => '/projects/turbo/hero.jpg'],
                    ['image' => '/projects/turbo/dashboard.jpg'],
                    ['image' => '/projects/turbo/menu.jpg'],
                    ['image' => '/projects/turbo/checkout.jpg'],
                    ['image' => '/projects/turbo/admin.jpg'],
                ],
                'metrics' => [
                    ['label' => 'Active Tenants', 'value' => '15+'],
                    ['label' => 'Orders Processed', 'value' => '10K+'],
                    ['label' => 'Test Coverage', 'value' => '85%'],
                ],
                'tags' => [
                    ['name' => 'laravel', 'color' => 'text-red-500'],
                    ['name' => 'react', 'color' => 'text-blue-500'],
                    ['name' => 'typescript', 'color' => 'text-blue-700'],
                    ['name' => 'tailwind', 'color' => 'text-green-400'],
                    ['name' => 'mysql', 'color' => 'pink-text-gradient'],
                ],
                'main_image' => '/projects/turbo/main.jpg',
                'source_code_link' => 'https://github.com/yourusername/turbo-restaurant',
                'duration' => '6 months',
                'team_size' => 'Solo Developer',
                'order' => 1,
            ],
            [
                'name' => 'Learning Piano Online',
                'description' => 'The project is an online learning platform that facilitates virtual education and collaboration. It includes features such as scheduling Zoom meetings, publishing articles, and...',
                'full_description' => 'An online learning platform that facilitates virtual education and collaboration for piano students and teachers. The platform includes comprehensive features for scheduling Zoom meetings, publishing educational articles, managing student progress, and providing interactive learning materials.',
                'problem' => 'Piano teachers and students needed a centralized platform to manage online lessons, track progress, and access learning materials. Traditional methods involved juggling multiple tools for video calls, content sharing, and progress tracking, leading to a fragmented learning experience.',
                'solution' => 'Built an integrated learning management system specifically designed for piano education. The platform combines video conferencing integration, content management, progress tracking, and interactive learning tools in one cohesive interface.',
                'role' => 'Fullstack Developer – Designed and implemented the entire platform from scratch.',
                'contributions' => [
                    'Integrated Zoom API for seamless lesson scheduling and management',
                    'Built content management system for articles and learning materials',
                    'Implemented student progress tracking and analytics dashboard',
                    'Created responsive UI with React and TypeScript',
                    'Designed database schema for users, lessons, and content',
                    'Implemented authentication and authorization system',
                ],
                'tech_stack' => [
                    [
                        'category' => 'Backend',
                        'items' => ['Laravel', 'MySQL', 'Zoom API'],
                    ],
                    [
                        'category' => 'Frontend',
                        'items' => ['React', 'TypeScript', 'Tailwind CSS'],
                    ],
                ],
                'challenges' => [
                    [
                        'title' => 'Zoom Integration Complexity',
                        'description' => 'Managing OAuth flow and webhook events from Zoom API while maintaining session state.',
                        'decision' => 'Implemented a dedicated service layer for Zoom operations with proper error handling and retry logic. Used Laravel queues for processing webhooks asynchronously.',
                    ],
                    [
                        'title' => 'Real-time Lesson Updates',
                        'description' => 'Students and teachers needed instant notifications about lesson changes and new content.',
                        'decision' => 'Leveraged Laravel Echo with Pusher for real-time notifications, ensuring both parties stay synchronized.',
                    ],
                ],
                'images' => [
                    ['image' => '/projects/lpo/main.jpg'],
                    ['image' => '/projects/lpo/dashboard.jpg'],
                    ['image' => '/projects/lpo/lessons.jpg'],
                ],
                'metrics' => null,
                'tags' => [
                    ['name' => 'react', 'color' => 'text-blue-500'],
                    ['name' => 'typescript', 'color' => 'text-blue-700'],
                    ['name' => 'tailwind', 'color' => 'text-green-400'],
                    ['name' => 'laravel', 'color' => 'text-red-500'],
                    ['name' => 'mysql', 'color' => 'pink-text-gradient'],
                ],
                'main_image' => '/projects/lpo/main.jpg',
                'source_code_link' => 'https://github.com/habibGamal/LPO_NEW',
                'duration' => '4 months',
                'team_size' => null,
                'order' => 2,
            ],
            [
                'name' => 'AIChE Student Chapter Website',
                'description' => 'The project is a student activity website that serves as a platform for publishing articles and sharing various materials such as images and PDF documents.',
                'full_description' => 'A comprehensive student activity website for the AIChE (American Institute of Chemical Engineers) student chapter. The platform serves as a hub for publishing articles, sharing educational materials, organizing events, and fostering community engagement among chemical engineering students.',
                'problem' => 'The student chapter needed a professional online presence to share knowledge, coordinate activities, and engage members. Existing solutions were either too generic or too expensive for a student organization budget.',
                'solution' => 'Developed a custom content management platform tailored to the chapter\'s needs, featuring article publishing, event management, resource sharing, and member engagement tools. The platform is cost-effective and easy for non-technical members to maintain.',
                'role' => 'Fullstack Developer – End-to-end development and deployment.',
                'contributions' => [
                    'Built custom CMS with intuitive admin interface',
                    'Implemented article publishing system with rich text editor',
                    'Created event management and calendar features',
                    'Developed file upload and management system for PDFs and images',
                    'Designed responsive UI matching organization branding',
                    'Optimized for performance and SEO',
                ],
                'tech_stack' => [
                    [
                        'category' => 'Backend',
                        'items' => ['Laravel', 'MySQL'],
                    ],
                    [
                        'category' => 'Frontend',
                        'items' => ['React', 'TypeScript', 'Tailwind CSS'],
                    ],
                ],
                'challenges' => [
                    [
                        'title' => 'Content Organization',
                        'description' => 'Managing diverse content types (articles, events, resources) with different access levels and publication workflows.',
                        'decision' => 'Implemented a flexible content type system with role-based permissions, allowing different workflows for different content categories.',
                    ],
                ],
                'images' => [
                    ['image' => '/projects/aiche/main.jpg'],
                    ['image' => '/projects/aiche/articles.jpg'],
                    ['image' => '/projects/aiche/events.jpg'],
                ],
                'metrics' => null,
                'tags' => [
                    ['name' => 'react', 'color' => 'text-blue-500'],
                    ['name' => 'typescript', 'color' => 'text-blue-700'],
                    ['name' => 'tailwind', 'color' => 'text-green-400'],
                    ['name' => 'laravel', 'color' => 'text-red-500'],
                    ['name' => 'mysql', 'color' => 'pink-text-gradient'],
                ],
                'main_image' => '/projects/aiche/main.jpg',
                'source_code_link' => 'https://github.com/habibGamal/aiche-remaster',
                'duration' => '3 months',
                'team_size' => null,
                'order' => 3,
            ],
            [
                'name' => 'Expense Tracker',
                'description' => 'The project consists of three main components: Expense Planning, Money Management, and Savings.',
                'full_description' => 'A comprehensive mobile application for personal finance management, featuring expense planning, money management, and savings tracking. The app helps users create personalized budgets, track spending, and achieve financial goals through intuitive visualizations and smart recommendations.',
                'problem' => 'People struggle to manage their finances effectively due to lack of visibility into spending patterns and difficulty maintaining budgets. Most finance apps are either too complex or lack the features needed for comprehensive money management.',
                'solution' => 'Created an intuitive mobile app that combines expense planning, real-time tracking, and savings goals in one place. The app uses smart categorization, visual analytics, and personalized insights to help users take control of their finances.',
                'role' => 'Mobile Developer – Solo development of the entire application.',
                'contributions' => [
                    'Designed and implemented expense planning algorithms',
                    'Built real-time expense tracking with categorization',
                    'Created savings goal management system',
                    'Implemented data visualization with charts and graphs',
                    'Designed intuitive mobile UI/UX',
                    'Implemented local data persistence',
                ],
                'tech_stack' => [
                    [
                        'category' => 'Mobile',
                        'items' => ['Flutter', 'Dart', 'SQLite'],
                    ],
                ],
                'challenges' => [
                    [
                        'title' => 'Offline-First Architecture',
                        'description' => 'Users needed to track expenses even without internet connectivity, with seamless sync when online.',
                        'decision' => 'Implemented local-first architecture using SQLite for data persistence, with optional cloud sync for backup and multi-device access.',
                    ],
                    [
                        'title' => 'Smart Categorization',
                        'description' => 'Automatically categorizing expenses based on description and merchant information.',
                        'decision' => 'Built a rule-based categorization system with machine learning-inspired pattern matching, learning from user corrections over time.',
                    ],
                ],
                'images' => [
                    ['image' => '/projects/money_app/main.jpg'],
                    ['image' => '/projects/money_app/dashboard.jpg'],
                    ['image' => '/projects/money_app/expenses.jpg'],
                ],
                'metrics' => null,
                'tags' => [
                    ['name' => 'flutter', 'color' => 'text-sky-500'],
                ],
                'main_image' => '/projects/money_app/main.jpg',
                'source_code_link' => 'https://github.com/habibGamal/money_app',
                'duration' => '2 months',
                'team_size' => null,
                'order' => 4,
            ],
            [
                'name' => 'Vilain E-Commerce Platform',
                'description' => 'A production-ready bilingual e-commerce platform built for Vilain, featuring a modern React-powered storefront with comprehensive inventory management, multi-tier promotion engine, and integrated payment processing.',
                'full_description' => 'Developed a full-stack e-commerce platform that addresses each business requirement through targeted features including bilingual interface (Arabic/English) with RTL support, advanced product catalog with variant management, intelligent search powered by TNT Search, dynamic shopping cart with automatic promotion application, multi-step checkout with address validation, region-aware shipping calculator based on Egyptian governorates, multi-layered promotion system, automated inventory tracking, and payment gateway integration with Kashier.',
                'problem' => 'Vilain needed a scalable e-commerce solution that could serve both Arabic and English-speaking customers while managing complex inventory scenarios including product variants, location-based shipping costs, and sophisticated promotional campaigns. The platform required seamless integration between customer-facing operations and administrative workflows, with support for multiple payment methods and order lifecycle management including returns and refunds.',
                'solution' => 'Built a comprehensive e-commerce platform with server-side rendered React components using Inertia.js for SEO optimization, type-safe development with TypeScript, responsive design system built with Shadcn/ui, payment gateway integration, web push notifications, and Docker containerization for consistent deployment.',
                'role' => 'Full-Stack Developer – Led the complete development lifecycle from database design to production deployment.',
                'contributions' => [
                    'Architected database schema supporting 25+ interconnected models with proper normalization',
                    'Implemented business logic across 15+ service classes for cart management, order processing, promotion calculations, and inventory control',
                    'Built RESTful APIs and Inertia.js controllers for seamless frontend-backend communication',
                    'Developed comprehensive factory and seeder system for realistic testing data',
                    'Integrated Kashier payment gateway with webhook handling for transaction verification',
                    'Built 40+ reusable React components following atomic design principles',
                    'Implemented responsive layouts supporting mobile-first design across all breakpoints',
                    'Created smooth animations and transitions using Framer Motion',
                    'Configured Docker multi-stage builds for development and production environments',
                    'Set up automated testing pipeline with PEST',
                ],
                'tech_stack' => [
                    ['category' => 'Backend', 'items' => ['Laravel 11', 'MySQL', 'Filament 3', 'Sanctum', 'Laravel Socialite']],
                    ['category' => 'Frontend', 'items' => ['React 18', 'TypeScript', 'Inertia.js', 'Shadcn/ui', 'Tailwind CSS', 'Framer Motion', 'i18next']],
                    ['category' => 'DevOps', 'items' => ['Vite', 'PEST', 'PHPStan', 'Laravel Pint', 'Docker']],
                    ['category' => 'Integrations', 'items' => ['Kashier Payment Gateway', 'TNT Search', 'Web Push Notifications']],
                ],
                'challenges' => [
                    ['title' => 'Bilingual Data Architecture', 'description' => 'Used column-level translation (name_en, name_ar) rather than separate translations table for improved performance at scale.'],
                    ['title' => 'Promotion Logic Complexity', 'description' => 'Implemented service-based architecture with separate condition evaluation and reward application logic for extensibility.'],
                    ['title' => 'Regional Shipping Calculations', 'description' => 'Built hierarchical location system allowing business users to adjust rates through admin panel without code changes.'],
                    ['title' => 'Type Safety Across Stack', 'description' => 'Established convention using index.d.ts files mirroring backend models for type consistency.'],
                ],
                'images' => [
                    ['image' => '/projects/vilain/home.jpg'],
                    ['image' => '/projects/vilain/products.jpg'],
                    ['image' => '/projects/vilain/cart.jpg'],
                    ['image' => '/projects/vilain/admin.jpg'],
                ],
                'metrics' => null,
                'tags' => [
                    ['name' => 'laravel', 'color' => 'red-text-gradient'],
                    ['name' => 'react', 'color' => 'blue-text-gradient'],
                    ['name' => 'typescript', 'color' => 'blue-text-gradient'],
                    ['name' => 'mysql', 'color' => 'pink-text-gradient'],
                ],
                'main_image' => '/projects/vilain/main.jpg',
                'source_code_link' => 'https://github.com/yourusername/vilain-ecommerce',
                'duration' => '8 months',
                'team_size' => 'Solo Developer',
                'order' => 5,
            ],
            [
                'name' => 'Sind-bad B2B Ecommerce Platform',
                'description' => 'A comprehensive B2B ecommerce platform designed for wholesale distributors in Arabic-speaking markets, unifying order management, inventory control, driver assignments, financial tracking, and customer relationship management.',
                'full_description' => 'An integrated business management platform connecting all stakeholders in the wholesale distribution chain. Features customer-facing mobile-optimized catalog, administrative backoffice, inventory management with stock counting and transfers, logistics coordination with driver tasks, financial operations including purchase invoices and cash settlements, and real-time notifications. Built mobile-first with full RTL Arabic support.',
                'problem' => 'Wholesale distributors operating in regional markets face fragmented workflows across ordering, inventory, delivery logistics, and financial accounting. Manual processes lead to stock discrepancies, delayed order fulfillment, and poor visibility into business performance. Existing B2B solutions often lack proper Arabic language support and fail to address unique operational needs of traditional wholesale businesses.',
                'solution' => 'Built an integrated platform with comprehensive reporting system featuring 15+ dynamic reports, real-time notification system using Laravel Reverb, mobile-first RTL-compatible UI, role-based access control with granular permissions across 50+ resources, and PDF invoice generation with customizable templates.',
                'role' => 'Fullstack Developer – Architected the complete application from database schema to frontend components.',
                'contributions' => [
                    'Architected complete application from database schema to frontend components',
                    'Implemented complex business logic for order processing, inventory management, and financial accounting',
                    'Built comprehensive reporting system with 15+ dynamic reports',
                    'Developed real-time notification system using Laravel Reverb and web push',
                    'Created mobile-first, RTL-compatible UI components using React and shadcn/ui',
                    'Integrated Inertia.js for seamless SPA experience',
                    'Implemented role-based access control with granular permissions',
                    'Designed and optimized database queries for large product catalogs',
                    'Built PDF invoice generation system',
                    'Established CI/CD practices with automated testing',
                ],
                'tech_stack' => [
                    ['category' => 'Backend', 'items' => ['Laravel 11', 'FilamentPHP 3', 'MySQL', 'Laravel Scout', 'Laravel Reverb', 'Laravel Sanctum']],
                    ['category' => 'Frontend', 'items' => ['React 18', 'TypeScript', 'Inertia.js 2', 'Tailwind CSS', 'shadcn/ui', 'Recharts', 'Laravel Echo']],
                    ['category' => 'Tools', 'items' => ['Pest PHP', 'PHPStan', 'Laravel Pint', 'Web Push Notifications']],
                ],
                'challenges' => [
                    ['title' => 'Data Consistency', 'description' => 'Implemented service-layer architecture with atomic transactions and audit trails for every stock movement.'],
                    ['title' => 'Real-time Updates', 'description' => 'Used Laravel Reverb for WebSocket connections with selective broadcasting for critical updates only.'],
                    ['title' => 'RTL Support', 'description' => 'Built direction-agnostic components using Radix UI primitives allowing runtime language switching.'],
                    ['title' => 'Complex Reporting', 'description' => 'Created dedicated report services with date range filtering, caching strategies, and export capabilities.'],
                ],
                'images' => [
                    ['image' => '/projects/sindbad/dashboard.jpg'],
                    ['image' => '/projects/sindbad/orders.jpg'],
                    ['image' => '/projects/sindbad/inventory.jpg'],
                    ['image' => '/projects/sindbad/reports.jpg'],
                ],
                'metrics' => null,
                'tags' => [
                    ['name' => 'laravel', 'color' => 'red-text-gradient'],
                    ['name' => 'react', 'color' => 'blue-text-gradient'],
                    ['name' => 'typescript', 'color' => 'blue-text-gradient'],
                    ['name' => 'mysql', 'color' => 'pink-text-gradient'],
                ],
                'main_image' => '/projects/sindbad/main.jpg',
                'source_code_link' => 'https://github.com/yourusername/sindbad-b2b',
                'duration' => '6 months',
                'team_size' => 'Solo Developer',
                'order' => 6,
            ],
            [
                'name' => 'Secure Education Platform',
                'description' => 'A comprehensive e-learning platform combining web-based course delivery with military-grade content protection through an encrypted desktop application.',
                'full_description' => 'Built a full-featured education platform that protects digital course content through video encryption and a secure desktop player. The system prevents unauthorized screen recording and downloading while providing seamless course purchasing, enrollment, and progress tracking. Videos are encrypted server-side using asymmetric encryption and can only be decrypted through the proprietary desktop player.',
                'problem' => 'Online education platforms face critical revenue loss from content piracy—students often record or download paid video courses and redistribute them. Traditional DRM solutions are expensive and easily bypassed. Education providers needed an affordable, effective way to protect their intellectual property while maintaining a smooth user experience.',
                'solution' => 'Developed a dual-component platform: a web application handling course discovery, purchases, and enrollment, paired with a secure desktop application for video playback. Implemented server-side RSA encryption, HLS streaming protocols, course management with structured blocks and resources, integrated payment processing with coupon support, progress tracking, and package bundles.',
                'role' => 'Fullstack Developer – Sole developer responsible for complete platform architecture and implementation.',
                'contributions' => [
                    'Designed and implemented secure video encryption workflow using RSA public key cryptography',
                    'Built RESTful API and business logic using Laravel framework',
                    'Developed relational database schema handling courses, enrollments, orders, and payments',
                    'Created comprehensive admin panel using Filament',
                    'Implemented authentication, authorization, and role-based access control',
                    'Integrated payment processing with transaction verification system',
                    'Built responsive web interface using React, TypeScript, and Inertia.js',
                    'Developed user dashboard for course browsing and progress tracking',
                    'Architected video encryption and secure delivery pipeline',
                    'Designed API integration between web platform and desktop application',
                ],
                'tech_stack' => [
                    ['category' => 'Backend', 'items' => ['Laravel 10', 'PHP 8.1', 'MySQL']],
                    ['category' => 'Frontend', 'items' => ['React 18', 'TypeScript', 'Inertia.js', 'TailwindCSS', 'Ant Design']],
                    ['category' => 'Security', 'items' => ['RSA Encryption', 'Laravel Sanctum', 'HLS Streaming', 'Video.js']],
                    ['category' => 'Admin', 'items' => ['Filament PHP']],
                ],
                'challenges' => [
                    ['title' => 'Content Protection Architecture', 'description' => 'Chose server-side RSA encryption paired with custom desktop player to create genuine technical barrier against piracy.'],
                    ['title' => 'Performance vs Security', 'description' => 'Implemented on-demand encryption with HLS streaming protocols to balance storage costs and performance.'],
                    ['title' => 'User Experience', 'description' => 'Designed one-time installation process with automatic license verification tied to user accounts.'],
                    ['title' => 'Scalable Course Structure', 'description' => 'Designed flexible three-tier content hierarchy (Courses → Blocks → Resources).'],
                ],
                'images' => [
                    ['image' => '/projects/education/courses.jpg'],
                    ['image' => '/projects/education/player.jpg'],
                    ['image' => '/projects/education/dashboard.jpg'],
                    ['image' => '/projects/education/admin.jpg'],
                ],
                'metrics' => null,
                'tags' => [
                    ['name' => 'laravel', 'color' => 'red-text-gradient'],
                    ['name' => 'react', 'color' => 'blue-text-gradient'],
                    ['name' => 'typescript', 'color' => 'blue-text-gradient'],
                    ['name' => 'mysql', 'color' => 'pink-text-gradient'],
                ],
                'main_image' => '/projects/education/main.jpg',
                'source_code_link' => 'https://github.com/yourusername/secure-education',
                'duration' => '5 months',
                'team_size' => 'Solo Developer',
                'order' => 7,
            ],
            [
                'name' => 'Multi-Tenant Clinic Management Platform',
                'description' => 'An enterprise-grade SaaS platform enabling medical clinics across Saudi Arabia to manage complete operations—from patient care and medical records to HR, inventory, and financial compliance.',
                'full_description' => 'A comprehensive multi-tenant SaaS platform that consolidates all clinic operations into a single, compliant system. Each clinic operates in an isolated database environment handling clinical operations (patient management, appointments, prescriptions, lab orders), business operations (inventory, accounting, invoicing), HR & workforce management (payroll, attendance, leave), compliance & integration (ZATCA e-invoicing, Tamara payments, WhatsApp API), and real-time features.',
                'problem' => 'Medical clinics in Saudi Arabia face fragmented workflows where patient management, inventory tracking, HR operations, and financial compliance exist in separate systems or manual processes. Small to mid-sized clinics lack access to affordable, integrated solutions that meet regulatory requirements like ZATCA e-invoicing while remaining scalable and user-friendly.',
                'solution' => 'Built a multi-tenant architecture serving isolated clinic instances with complete patient lifecycle management, appointment scheduling, digital prescriptions, laboratory processing, specialty-specific modules, full inventory management, integrated accounting, HR & payroll processing, ZATCA e-invoicing compliance, and real-time notifications using Laravel Echo and Reverb.',
                'role' => 'Full-Stack Developer & Team Manager – Led 3-person development team through 3-month intensive development cycle.',
                'contributions' => [
                    'Architected multi-tenant infrastructure using Stancl/Tenancy with database isolation for 50+ clinic deployments',
                    'Designed domain-driven architecture with clear separation between central and tenant contexts',
                    'Established development workflows, code standards, and CI/CD processes using Pest',
                    'Built complete accounting module with double-entry bookkeeping and automated transaction recording',
                    'Developed ZATCA e-invoicing integration ensuring compliance with Saudi tax regulations',
                    'Implemented patient invoice system with complex pricing logic and multi-payment methods',
                    'Created inventory management system with batch tracking and expiration monitoring',
                    'Designed payroll calculation engine handling Saudi labor law requirements',
                    'Built real-time features using Laravel Reverb and Echo',
                    'Mentored junior developers on Laravel and React best practices',
                ],
                'tech_stack' => [
                    ['category' => 'Backend', 'items' => ['Laravel 12', 'PHP 8.4', 'Stancl/Tenancy', 'Laravel Reverb', 'MySQL']],
                    ['category' => 'Frontend', 'items' => ['React 19', 'TypeScript', 'Inertia.js v2', 'Tailwind CSS v4', 'shadcn/ui', 'Radix UI']],
                    ['category' => 'Integrations', 'items' => ['ZATCA e-invoicing', 'Tamara Payment Gateway', 'WhatsApp Business API']],
                    ['category' => 'Tools', 'items' => ['Pest PHP', 'Laravel Sail', 'Vite', 'FullCalendar', 'Chart.js']],
                ],
                'challenges' => [
                    ['title' => 'Multi-Tenancy Architecture', 'description' => 'Implemented database-per-tenant architecture providing superior data isolation and regulatory compliance guarantees.'],
                    ['title' => 'Complex Inventory', 'description' => 'Designed warehouse-items-batches architecture maintaining batch-level granularity for complete traceability.'],
                    ['title' => 'ZATCA E-Invoicing', 'description' => 'Achieved 100% compliance with ZATCA Phase 2 requirements using cryptographically signed invoices.'],
                    ['title' => 'Payroll Calculation', 'description' => 'Created modular payslip calculation engine with detailed audit trails for each calculation step.'],
                ],
                'images' => [
                    ['image' => '/projects/clinic/dashboard.jpg'],
                    ['image' => '/projects/clinic/patients.jpg'],
                    ['image' => '/projects/clinic/inventory.jpg'],
                    ['image' => '/projects/clinic/invoicing.jpg'],
                ],
                'metrics' => [
                    ['label' => 'Clinic Deployments', 'value' => '50+'],
                    ['label' => 'Team Size', 'value' => '3 Developers'],
                    ['label' => 'ZATCA Compliance', 'value' => '100%'],
                ],
                'tags' => [
                    ['name' => 'laravel', 'color' => 'red-text-gradient'],
                    ['name' => 'react', 'color' => 'blue-text-gradient'],
                    ['name' => 'typescript', 'color' => 'blue-text-gradient'],
                    ['name' => 'mysql', 'color' => 'pink-text-gradient'],
                ],
                'main_image' => '/projects/clinic/main.jpg',
                'source_code_link' => 'https://github.com/yourusername/clinic-platform',
                'duration' => '3 months',
                'team_size' => '3 Developers (Team Manager)',
                'order' => 8,
            ],
            [
                'name' => 'Turbo Restaurant POS',
                'description' => 'A comprehensive cloud-based restaurant management system that streamlines operations from orders to inventory, built for the Egyptian market.',
                'full_description' => 'An end-to-end restaurant management platform designed to handle point-of-sale transactions, inventory tracking, financial reporting, and customer relationships. The system delivers real-time updates, automated receipt printing, and comprehensive analytics featuring automated inventory intelligence with recipe-based ingredient deduction, comprehensive business analytics, and multi-role access for cashiers, kitchen staff, managers, and owners.',
                'problem' => 'Restaurant operations involve dozens of interconnected processes—taking orders, tracking inventory, managing staff shifts, processing payments, and generating financial reports. Traditional solutions often require multiple disconnected systems, leading to data inconsistencies, manual reconciliation, and lost revenue through inventory shrinkage or pricing errors.',
                'solution' => 'Consolidated all restaurant operations into a single platform with real-time operational control where every action updates instantly across all stations, automated inventory intelligence connecting recipes to raw material consumption, and comprehensive business analytics with pre-built reports surfacing actionable insights.',
                'role' => 'Full-Stack Developer – Architected and implemented the complete application stack, from database design through user interface.',
                'contributions' => [
                    'Designed and executed migration from legacy AdonisJS to Laravel + FilamentPHP stack',
                    'Established clean architecture patterns using repositories, services, DTOs, and action classes',
                    'Implemented event-driven architecture for inventory updates and notifications',
                    'Built dual-interface system: FilamentPHP admin panel and React-based POS interface',
                    'Created complete order lifecycle from cart assembly through payment processing',
                    'Developed automated stock tracking with recipe-based ingredient deduction',
                    'Built shift-based cash control system with comprehensive daily reporting',
                    'Integrated network thermal printers with automatic order distribution',
                    'Designed Arabic-first interface with RTL support and EGP currency handling',
                    'Established comprehensive test suite using Pest with CI/CD automation',
                ],
                'tech_stack' => [
                    ['category' => 'Backend', 'items' => ['Laravel 11', 'FilamentPHP 4', 'MySQL', 'Redis']],
                    ['category' => 'Frontend', 'items' => ['React 18', 'Inertia.js', 'shadcn/ui', 'Ant Design', 'Tailwind CSS']],
                    ['category' => 'Infrastructure', 'items' => ['Vite', 'Pest', 'PHPStan', 'Laravel Pint', 'ESC/POS']],
                ],
                'challenges' => [
                    ['title' => 'Live System Migration', 'description' => 'Implemented parallel-running strategy for two weeks allowing staff training while maintaining business continuity.'],
                    ['title' => 'Recipe-Based Inventory', 'description' => 'Implemented weighted average cost system recalculating product costs with each purchase invoice.'],
                    ['title' => 'Network Printer Reliability', 'description' => 'Designed queuing system with automatic retries and browser notifications for failed print jobs.'],
                    ['title' => 'Real-Time Accuracy', 'description' => 'Implemented database row-level locking preventing inventory overselling during peak periods.'],
                ],
                'images' => [
                    ['image' => '/projects/turbo_pos/pos.jpg'],
                    ['image' => '/projects/turbo_pos/inventory.jpg'],
                    ['image' => '/projects/turbo_pos/reports.jpg'],
                    ['image' => '/projects/turbo_pos/kitchen.jpg'],
                ],
                'metrics' => [
                    ['label' => 'Concurrent Users', 'value' => '50+'],
                    ['label' => 'Development Time', 'value' => 'Reduced by 40%'],
                ],
                'tags' => [
                    ['name' => 'laravel', 'color' => 'red-text-gradient'],
                    ['name' => 'react', 'color' => 'blue-text-gradient'],
                    ['name' => 'filament', 'color' => 'green-text-gradient'],
                    ['name' => 'mysql', 'color' => 'pink-text-gradient'],
                ],
                'main_image' => '/projects/turbo_pos/main.jpg',
                'source_code_link' => 'https://github.com/yourusername/turbo-restaurant-pos',
                'duration' => '4 months',
                'team_size' => 'Solo Developer',
                'order' => 9,
            ],
        ];

        foreach ($works as $work) {
            Work::create($work);
        }
    }
}
